# Generated by Django 4.1.6 on 2023-04-08 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_amount', models.IntegerField()),
                ('paid', models.BooleanField(default=False)),
                ('customer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_by_customer_num', to='travello.confirmbooking', verbose_name='Customer Number')),
                ('customer_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_by_customer_name', to='travello.confirmbooking', verbose_name='Customer Name')),
            ],
        ),
    ]
