# Generated by Django 4.1.6 on 2023-04-11 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0002_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='Domestic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='destination',
            name='International',
            field=models.BooleanField(default=False),
        ),
    ]
