# Generated by Django 4.1.6 on 2023-04-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0004_payment_razor_pay_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='img4',
            field=models.ImageField(default=True, upload_to='pics'),
        ),
        migrations.AddField(
            model_name='destination',
            name='img5',
            field=models.ImageField(default=True, upload_to='pics'),
        ),
        migrations.AddField(
            model_name='destination',
            name='img6',
            field=models.ImageField(default=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='day1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='day10',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='day11',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='day12',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='day13',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='day14',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='day15',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='day16',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='day2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='day3',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='day4',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='day5',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='day6',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='day7',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='day8',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='day9',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
