# Generated by Django 4.1.6 on 2023-04-12 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0005_destination_img4_destination_img5_destination_img6_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='img6',
        ),
    ]
